Echinochloa crus galli: Echinochloa crus-galli
Citrus clementina: Citrus x clementina
Cinnamomum kanehirae: Cinnamomum micranthum f. kanehirae
Fragaria ananassa: Fragaria x ananassa
Petunia hybrida: Petunia x hybrida
Poncirus trifoliata: Citrus trifoliata
Physcomitrella patens: Physcomitrium patens
Microsechium compositum: Sechium compositum
Sechium tacaco: Frantzia tacaco
Sechium pittieri: Frantzia pittieri
